#!/bin/bash

i=0
progress=""

while true; do
	notify-send -u critical -i ~/pomodorotimer/pomodoro.png "Focus" "Time to work."
	echo "Press Enter to start your work period."
	read response
	sleep 1s
	progress=${progress}" \xE2\x9C\x93" #Add a check mark (UTF-8 code) to progress made
	echo -e "Pomodoros Accomplished: $progress"
	i=$((i + 1))
	if [ "$i" -lt 4 ]; then
		notify-send -u critical -i ~/pomodorotimer/pomodoro.png "Relax" "Time to take a short break."
		echo "Press Enter to begin your break period." 
		read response
		sleep 1s
	else
		notify-send -u critical -i ~/pomodorotimer/pomodoro.png "Relax - You've earned it." "Time to take a longer break."
		echo "Press Enter to begin your longer break period." 
		read response
		sleep 1s
		i=0
	fi	

done

exit 0
